### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by nsheff** [databio/bedstat-rest-api#1]
Can you update the instructions so that they show how to run this in a container instead?

Basically I think they should follow the [refgenieserver README pattern](https://github.com/databio/refgenieserver)

**Comment by oddodaoddo** [comment]
@nsheff Ok - I think this would be one way to do it, that I came up with. Let me know what you think.

**Comment by oddodaoddo** [comment]
Just added the instructions on how to run everything, sorry for multiple commits on an issue branch, I made a mistake in the original commit and then reverted only to realize I made a mistake reverting. Sigh.

**Comment by oddodaoddo** [comment]
From the discussion in #9 I infer that the Docker setup works. Hence, I am closing this issue.
