### ISSUE TITLE
software is now broken

### ISSUE THREAD

**Issue by nsheff** [databio/bedstat-rest-api#10]
When I merged in everything, it no longer works.

```
python3.7 main.pyemail-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
```

I realized there's no more `main` section in main.py... I guess you weren't intending this to work and I shouldn't have merged? I was just trying to clean up everything.

**Comment by oddodaoddo** [comment]
It should work, it works for me (from Docker). If you want to run it from the command line:
```
uvicorn main:app --reload
```
I will add that to the README.

**Comment by nsheff** [comment]
The readme still said "python3 main.py"

**Comment by nsheff** [comment]
Ok, yes, the `uvicorn` command works!

**Comment by oddodaoddo** [comment]
Fixed README (in dev).
